version: '3.1'

services:
  psql_clean_arc_api:
    container_name: psql_clean_arc_api
    hostname: psql_clean_arc_api
    image: postgres
    restart: "no"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: development_password
      POSTGRES_DB: database_name
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
        - ~/.PostgressData/postgresonly/psql_clean_arc_api:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
